server:
  port: 8080
  #ssl:
    #key-alias: server
    #key-store-type: JKS
    #key-store: classpath:ssl/150smc.com.jks
    #key-store-password: e8ffji1lb7s449t
spring:
  #数据源配置
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://1.15.146.24:5432/quartz
      username: windy
      password: windymama@.com

wx:
  app-id: wx1141b89fbe95fa0b
  app-secret: 12748d6dbeec25014d243b3f534b5e6d
  url: https://api.weixin.qq.com
  auth-code2Session: ${wx.url}/sns/jscode2session?appid=${wx.app-id}&secret=${wx.app-secret}



mybatis-plus:
  # mapper配置文件路径
  mapperLocations: classpath*:com/windy/user/dao/mapper/*Mapper.xml
  #数据库对应对象实例包
  typeAliasesPackage: com/windy/user/entity
  configuration:
    #mybatis-plus配置控制台打印完整带参数SQL语句，用于debug调试查看完整查询SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
    #主键类型 0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
